import avatarDefault from '../assets/avatar-default.png'

export const columns = [
    {
        title: '号码',
        field: 'jerseyNum',
        width: 100,
    },
    {
        title: '位置',
        field: 'position',
        width: 100,
    },
    {
        title: '年龄',
        field: 'age',
        width: 100,
    },
    {
        title: '得分',
        field: 'score',
        width: 100,
    },
    {
        title: '篮板',
        field: 'backboard',
        width: 100,
    },
    {
        title: '助攻',
        field: 'assists',
        width: 100,
    },
]

export const columns1 = [
    {
        title: '号码',
        field: 'jerseyNum',
        width: 100,
        fixed: true,
    },
    {
        title: '位置',
        field: 'position',
        width: 100,
        fixed: true,
    },
    {
        title: '年龄',
        field: 'age',
        width: 100,
    },
    {
        title: '得分',
        field: 'score',
        width: 100,
    },
    {
        title: '篮板',
        field: 'backboard',
        width: 100,
    },
    {
        title: '助攻',
        field: 'assists',
        width: 100,
    },
    {
        title: '投篮',
        field: 'rebounds',
        width: 100,
    },
    {
        title: '三分命中率',
        field: 'threesPCT',
        width: 100,
    },
    {
        title: '罚球命中率',
        field: 'ftPCT',
        width: 100,
    },
]

export const columns2 = [
    {
        field: 'name',
        title: '球队名',
        formatter (rowData) {
            return `<div class="player-info">
                <div class="player-logo">
                    <img src="${rowData.logo || avatarDefault}" onerror="this.onerror = ''; this.src = '${avatarDefault}'">
                </div>
                <div class="player-cnname">${rowData.name}</div>
            </div>`
        },
        width: 155,
        fixed: true,
    },
    {
        title: '号码',
        field: 'jerseyNum',
        width: 100,
        titleCellClass: 'jersey-num-highlight',
    },
    {
        title: '位置',
        field: 'position',
        width: 100,
    },
    {
        title: '年龄',
        field: 'age',
        width: 100,
    },
    {
        title: '得分',
        field: 'score',
        width: 100,
    },
    {
        title: '篮板',
        field: 'backboard',
        width: 100,
    },
    {
        title: '助攻',
        field: 'assists',
        width: 100,
    },
    {
        title: '投篮',
        field: 'rebounds',
        width: 100,
    },
    {
        title: '三分命中率',
        field: 'threesPCT',
        width: 100,
    },
    {
        title: '罚球命中率',
        field: 'ftPCT',
        width: 100,
    },
]

// rem 单位宽度
export const columns3 = [
    {
        title: '号码',
        field: 'jerseyNum',
        width: 0.5,
        fixed: true,
    },
    {
        title: '位置',
        field: 'position',
        width: 0.5,
    },
    {
        title: '年龄',
        field: 'age',
        width: 0.5,
    },
    {
        title: '得分',
        field: 'score',
        width: 0.5,
    },
    {
        title: '篮板',
        field: 'backboard',
        width: 0.5,
    },
    {
        title: '助攻',
        field: 'assists',
        width: 0.5,
    },
    {
        title: '投篮',
        field: 'rebounds',
        width: 0.5,
    },
    {
        title: '三分命中率',
        field: 'threesPCT',
        width: 0.5,
    },
    {
        title: '罚球命中率',
        field: 'ftPCT',
        width: 0.5,
    },
]

export const list = [
    {
        playerId: '88621',
        name: '帕森斯',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '前锋',
        age: '30',
        jerseyNum: '0',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88621&competitionId=100000',
    },
    {
        playerId: '88628',
        name: '帕克',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '前锋',
        age: '24',
        jerseyNum: '5',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88628&competitionId=100000',
    },
    {
        playerId: '88686',
        name: '特纳',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫-前锋',
        age: '30',
        jerseyNum: '0',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88686&competitionId=100000',
    },
    {
        playerId: '88689',
        name: '杰伦-亚当斯',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫',
        age: '23',
        jerseyNum: '10',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88689&competitionId=100000',
    },
    {
        playerId: '88690',
        name: '安德森',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫-前锋',
        age: '25',
        jerseyNum: '1',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88690&competitionId=100000',
    },
    {
        playerId: '88692',
        name: '本布里',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫-前锋',
        age: '25',
        jerseyNum: '95',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88692&competitionId=100000',
    },
    {
        playerId: '88693',
        name: '卡特',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫-前锋',
        age: '42',
        jerseyNum: '15',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88693&competitionId=100000',
    },
    {
        playerId: '88696',
        name: '科林斯',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '前锋',
        age: '21',
        jerseyNum: '20',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88696&competitionId=100000',
    },
    {
        playerId: '88704',
        name: '凯文-赫尔特',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫',
        age: '20',
        jerseyNum: '3',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88704&competitionId=100000',
    },
    {
        playerId: '88706',
        name: '莱恩',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '中锋',
        age: '26',
        jerseyNum: '25',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88706&competitionId=100000',
    },
    {
        playerId: '88710',
        name: '波斯里斯',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '前锋',
        age: '25',
        jerseyNum: '22',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88710&competitionId=100000',
    },
    {
        playerId: '88717',
        name: '特雷-杨',
        logo: 'http://nbachina.qq.com/media/img/players/head/260x190/1629121.png',
        position: '后卫',
        age: '20',
        jerseyNum: '11',
        score: '0.0',
        backboard: '0.0',
        assists: '0.0',
        rebounds: '0.0',
        threesPCT: '0%',
        ftPCT: '0%',
        offensiveRebounds: '0.0',
        defensiveRebounds: '0.0',
        turnovers: '0.0',
        blocks: '0.0',
        fouls: '0.0',
        competitionId: '100000',
        detailUrl: 'https://kbsapp.sports.qq.com/player/data?playerId=88717&competitionId=100000',
    },
]
